require: rubocop-performance

AllCops:
  TargetRubyVersion: 2.5
  TargetRailsVersion: 5.2
  DisplayCopNames: true
  Exclude:
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'db/**/*'

Rails:
  Enabled: true

Documentation:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Metrics/LineLength:
  Exclude:
    - 'app/controllers/**/*'
    - 'spec/**/*'

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'config/environments/*.rb'
    - 'config/routes.rb'
    - 'spec/**/*'
